name: citizen_printer_ios
description: iOS implementation of the citizen_printer plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: citizen_printer
    platforms:
      ios:
        pluginClass: CitizenPrinterPlugin
        dartPluginClass: CitizenPrinterIOS

dependencies:
  flutter:
    sdk: flutter
  citizen_printer_platform_interface:
    path: ../citizen_printer_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^2.4.0
