name: citizen_printer
description: Citizen SDK Plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: citizen_printer_android
      ios:
        default_package: citizen_printer_ios

dependencies:
  flutter:
    sdk: flutter
  citizen_printer_android:
    path: ../citizen_printer_android
  citizen_printer_ios:
    path: ../citizen_printer_ios
  citizen_printer_platform_interface:
    path: ../citizen_printer_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^2.4.0
